### ISSUE TITLE
Unable to Clone Wiki

### ISSUE THREAD

**Issue by MrAsynchronous** [p3lim/lua-doc-parser#2]
Using the example provided in the README.  Unable to clone the .wiki. 

![image](https://user-images.githubusercontent.com/5618200/95274410-bdfff080-0813-11eb-9972-602d369f5693.png)

**Comment by p3lim** [comment]
You'll have to ask https://github.com/actions/checkout, but my first guess is that you don't have a wiki.

**Comment by MrAsynchronous** [comment]
I’ve added the wiki. How do I set the input directory to read all files in the src container?

**Comment by p3lim** [comment]
> How do I set the input directory to read all files in the src container?

What do you mean?

**Comment by MrAsynchronous** [comment]
So the action is successful, but it doesn't write any documentation. I don't think it's finding the right folder to read the Lua files. Very new to actions.

**Comment by p3lim** [comment]
It looks everywhere for Lua files, including every subdirectory in the repository. The only requirement is that it has the ".lua" suffix.

**Comment by p3lim** [comment]
I can see you're attempting to use it with this repository: https://github.com/Palm-Studio/MicroCity

The action runs just fine, but you don't have any documentation in those files in the correct format, you seem to be using PanDoc notation, which this does not support.

See the readme for the documentation on how to format it, and one of my projects for an actual example (e.g. [LibDropDown](https://github.com/p3lim-wow/LibDropDown/blob/master/LibDropDown.lua)).

**Comment by p3lim** [comment]
If you use `@master` instead of `@v2` right now it'll show an output of how many files it didn't find any documentation in, just to show that it actually parsed all the files. I'm not bumping the version for that change though.

**Comment by MrAsynchronous** [comment]
Can't believe I forgot to change the comment styling.  All working.  Just out of curiosity, is it possible to pipe the files into an mkdocs folder?

**Comment by p3lim** [comment]
You can put them wherever you want, see the output option.
